server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.example: DEBUG

phone-to-country:
  calling-code-wiki:
    url: "https://en.wikipedia.org/wiki/List_of_country_calling_codes"
    table-selector: "#bodyContent table.wikitable:first-of-type"
